/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoice;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  java.sql.Timestamp;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author ASUS
 */
public class GenerateInvoice extends javax.swing.JFrame {
    private ManageInvoice previousFrame;
    private DefaultTableModel tableModel;
    private Invoice invoice;
    private ArrayList<product> productts;
    productManagement pd;
    private ArrayList<invoiceDetail> details;
    int index;
    invoiceDetailManagement idm;
    InvoiceManagement im;
    float moneyTotal;
    public int employee_id;
    /**
     * Creates new form invoice 
     */
    public GenerateInvoice() {
        initComponents();
        setLocationRelativeTo(null);
        invoice = new Invoice();
        tableModel = (DefaultTableModel) tblInvoice.getModel();
        pd = new productManagement();
        details = new ArrayList<>();
        index=0;
        productts=new ArrayList<>();
        idm = new invoiceDetailManagement();
        moneyTotal=0;
        im = new InvoiceManagement();
       SpinnerNumberModel spinnerModel = (SpinnerNumberModel) spinnerQuantity.getModel();
       spinnerModel.setMinimum(0);
    }
    public GenerateInvoice(int id) {
        initComponents();
        setLocationRelativeTo(null);
        invoice = new Invoice();
        tableModel = (DefaultTableModel) tblInvoice.getModel();
        pd = new productManagement();
        details = new ArrayList<>();
        index=0;
        productts=new ArrayList<>();
        idm = new invoiceDetailManagement();
        moneyTotal=0;
        im = new InvoiceManagement();
       SpinnerNumberModel spinnerModel = (SpinnerNumberModel) spinnerQuantity.getModel();
       spinnerModel.setMinimum(0);
       employee_id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddInvoice = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPaymentMethod = new javax.swing.JComboBox<>();
        spinnerQuantity = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice Option");
        setUndecorated(true);
        setResizable(false);

        btnAddInvoice.setText("Generate invoice");
        btnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvoiceActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing "));
        jPanel1.setName("dfdsfs"); // NOI18N
        jPanel1.setVerifyInputWhenFocusTarget(false);

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Description", "Price", "Quantity", "Expiration Date", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInvoice);

        jLabel1.setText("Product ID:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton2.setText("Log out");

        btnDelete.setText("Delete row");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity: ");

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        lbTotal.setText("Total");

        jLabel4.setText("Payment method");

        cbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Bank transfer" }));
        cbPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaymentMethodActionPerformed(evt);
            }
        });

        spinnerQuantity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerQuantity.setDoubleBuffered(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(34, 34, 34)
                .addComponent(lbTotal)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(spinnerQuantity))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddProduct)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(lbTotal)
                    .addComponent(jLabel4)
                    .addComponent(cbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnAddInvoice)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddInvoice)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        previousFrame = new ManageInvoice();
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvoiceActionPerformed
        // TODO add your handling code here:
        if(index ==0) {
              JOptionPane.showMessageDialog(null, "You have to add product!");
              return;
        }
        Timestamp currentTimestamp = new Timestamp(System.currentTimeMillis());
        Invoice invoice = new Invoice();
        invoice.setTotal_amount(moneyTotal);
        invoice.setPayment_method(cbPaymentMethod.getSelectedItem().toString());
        invoice.setPayment_status(false);
        invoice.setCreated_at(currentTimestamp);
        invoice.setEmployee_id(employee_id);
        int id = im.writeInvoiceUsingPrepareStatement(invoice);
        for (invoiceDetail x : details) {
            x.setInvoice_id(id);
        }
        idm.writeInvoicesDetailUsingPrepareStatement(details);
        JOptionPane.showMessageDialog(null, "General Invoice success!");
    }//GEN-LAST:event_btnAddInvoiceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
   if(index==0) {
       JOptionPane.showMessageDialog(rootPane, "No row to delete");
   }
   Float value = (Float) tableModel.getValueAt(index, 6);
   if(value != null) {
    float cellValue = (Float) value;
    moneyTotal -= cellValue;
    tableModel.removeRow(index);
    productts.remove(index-1);
    index--;
    tableModel.fireTableDataChanged(); 
     lbTotal.setText("Total: "+ moneyTotal);
    
   }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        int quantity = (int) spinnerQuantity.getValue();
        if(id.isEmpty()) {
             JOptionPane.showMessageDialog(this,
                     "You have to type id product and quantity of them",
                     "Eror",JOptionPane.ERROR_MESSAGE);
             return;
         }
        try {
        // Chuyển đổi giá trị sang kiểu số nguyên
         var product_id = Integer.parseInt(id);
         //var productt_quantity = Integer.parseInt(quantity);
        // Gọi phương thức tìm kiếm với giá trị invoiceID
        product productt = pd.searchProductUsingPrepareStatement(product_id);
        if(productt.getProduct_id() ==0 ) {
           JOptionPane.showMessageDialog(null, "this product doesn't existed!");
           txtID.setText("");
          spinnerQuantity.setValue(0);
           return;
        }
        productts.add(productt);
        var detail = new invoiceDetail(productt.getProduct_id(),quantity,productt.getPrice());
        details.add(detail);
        showProductBill(productt,quantity);
        index++;
        // Xóa nội dung trong trường nhập liệu
       txtID.setText("");
       spinnerQuantity.setValue(0);
    } catch (NumberFormatException e) {
        // Xử lý lỗi khi giá trị nhập vào không phải là số nguyên
        JOptionPane.showMessageDialog(this, "ID of product and quantity is a interger", "Eror", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void cbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaymentMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaymentMethodActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInvoice;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbPaymentMethod;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

    private void showProductBill(product productt,int quantity) {
        float total = quantity* productt.getPrice();
        moneyTotal +=total;
       var row = new Object[] {
     productt.getProduct_id(),productt.getProduct_name(),productt.getDescription()
               ,productt.getPrice(), quantity , productt.getExperation_date(),total
  };
  tableModel.addRow(row);
  tableModel.fireTableDataChanged();
  lbTotal.setText("Total: "+ moneyTotal);
    }
}
