/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SignInUp;

import User.userController;
import SignInUp.Login;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ForgotPassword extends javax.swing.JFrame {
     Color notEdit = new Color (204,204,204);
     Color edit = new Color (255,255,255);
     userController user; 
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        init();
        user = new userController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cbbQuestion = new javax.swing.JComboBox<>();
        txtAnswer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labelHide = new javax.swing.JLabel();
        labelShow = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        labelSearch = new javax.swing.JLabel();
        txtNewpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(25, 118, 221));
        jPanel1.setForeground(new java.awt.Color(25, 118, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("#9Slide01 Tieu de ngan", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, -1));

        txtUsername.setFont(new java.awt.Font("#9Slide02 Noi dung dai", 0, 16)); // NOI18N
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 30));

        cbbQuestion.setFont(new java.awt.Font("#9Slide02 Noi dung dai", 0, 16)); // NOI18N
        cbbQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What are your favorite hobbies?", "Do you enjoy outdoor activities or indoor activities more?", "What type of books do you like to read?", "Are you into sports? If so, which ones?", "Do you have any favorite movies or TV shows?", "Are you a fan of music? What genres do you enjoy listening to?", "What is your favorite type of cuisine or food?", "Do you have any particular travel destinations that you love?", "Are you interested in art? What forms of art do you appreciate?", "Do you have any favorite video games or board games?" }));
        cbbQuestion.setSelectedIndex(-1);
        jPanel1.add(cbbQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 310, 30));

        txtAnswer.setFont(new java.awt.Font("#9Slide02 Noi dung dai", 0, 16)); // NOI18N
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 310, 30));

        jLabel2.setFont(new java.awt.Font("#9Slide01 Noi dung ngan", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("#9Slide01 Noi dung ngan", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("#9Slide01 Noi dung ngan", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Security question?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("#9Slide01 Noi dung ngan", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Answer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(25, 118, 221));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 37, -1));

        labelHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hide.png"))); // NOI18N
        labelHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHideMouseClicked(evt);
            }
        });
        jPanel1.add(labelHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 30));

        labelShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/visible.png"))); // NOI18N
        labelShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelShowMouseClicked(evt);
            }
        });
        jPanel1.add(labelShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 30));

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(25, 118, 221));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 40));

        labelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        labelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSearchMouseClicked(evt);
            }
        });
        jPanel1.add(labelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));
        jPanel1.add(txtNewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(isEmpty() && user.checkInforToGetNewPass(txtUsername.getText(), cbbQuestion.getSelectedItem().toString(), txtAnswer.getText())) {
            boolean x = user.UpdateNewPass(String.valueOf(txtNewpass.getPassword()), txtUsername.getText());
            if(x) {
                 JOptionPane.showMessageDialog(null, "Repassword account success, you try login!", "Notice", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        else {
            JOptionPane.showMessageDialog(this, "You have to fill full of texts and check formal", "Warning", 2);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                for(double i=0.1;i<=1.0;i+=0.1) {
            String s=""+i;
                float f = Float.parseFloat(s);
                this.setOpacity(f);
            try {
                Thread.sleep(40);
            } catch (InterruptedException ex) {
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void labelHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHideMouseClicked
        // TODO add your handling code here:
        txtNewpass.setEchoChar((char)0);
        labelHide.setVisible(false);
        labelShow.setVisible(true);
    }//GEN-LAST:event_labelHideMouseClicked

    private void labelShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelShowMouseClicked
        // TODO add your handling code here:
        txtNewpass.setEchoChar((char) '*');
        labelHide.setVisible(true);
        labelShow.setVisible(false);
    }//GEN-LAST:event_labelShowMouseClicked

    private void labelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSearchMouseClicked
        // TODO add your handling code here:
        if(user.checkUsername(txtUsername.getText()))  {
           JOptionPane.showMessageDialog(this, "Username not existed", "Warning", 2);
             return;
        }
        else {
            cbbQuestion.setBackground(edit);
       txtAnswer.setBackground(edit);
       txtNewpass.setBackground(edit);
       cbbQuestion.setEditable(true);
       txtAnswer.setEditable(true);
       txtNewpass.setEditable(true);
       btnSave.setEnabled(true);
        }
    }//GEN-LAST:event_labelSearchMouseClicked

    private boolean isEmpty() {
         if(txtUsername.getText().isEmpty()) {
             JOptionPane.showMessageDialog(this, "Username is required", "Warning", 2);
            return false;
        }
        if(String.valueOf(txtNewpass.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password is required", "Warning", 2);
             return false;
        }
        int lengthPassword = txtNewpass.getPassword().length; 
        if(lengthPassword <= 6) {
            JOptionPane.showMessageDialog(this, "Password is not formal (at least 7 characters)", "Warning", 2);
             return false;
        }
         return true;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbbQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHide;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelShow;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JPasswordField txtNewpass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void init() {
       cbbQuestion.setBackground(notEdit);
       txtAnswer.setBackground(notEdit);
       txtNewpass.setBackground(notEdit);
       cbbQuestion.setEditable(false);
       txtAnswer.setEditable(false);
       txtNewpass.setEditable(false);
       btnSave.setEnabled(false);
    }
}
