/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SignInUp;

import Employee.AdminDashBoard;
import Employee.Employee_Dashboard;
import User.userDashBoard;
import SignInUp.SignUP;
import User.userController;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    private userController user= new userController();

    
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        init();
        user = new userController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelHide = new javax.swing.JLabel();
        rbtnUser = new javax.swing.JRadioButton();
        rbtnAdmin = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lableSignUp = new javax.swing.JLabel();
        lableForgotPassword = new javax.swing.JLabel();
        lableShow = new javax.swing.JLabel();
        rbEmployee = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 194, 150));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trolley.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        jLabel3.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TO");

        jLabel4.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ONLINE");

        jLabel5.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SHOPPING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        jPanel2.setBackground(new java.awt.Color(42, 58, 73));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 0, 37, -1));

        jLabel7.setBackground(new java.awt.Color(42, 58, 73));
        jLabel7.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Login");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, -1));
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 302, 30));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 302, 30));

        jLabel8.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        labelHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hide.png"))); // NOI18N
        labelHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHideMouseClicked(evt);
            }
        });
        jPanel2.add(labelHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 30));

        buttonGroup1.add(rbtnUser);
        rbtnUser.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        rbtnUser.setForeground(new java.awt.Color(255, 255, 255));
        rbtnUser.setText("User");
        rbtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUserActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 80, -1));

        buttonGroup1.add(rbtnAdmin);
        rbtnAdmin.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        rbtnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAdmin.setText("Admin");
        rbtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAdminActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, -1));

        btnLogin.setBackground(new java.awt.Color(64, 194, 150));
        btnLogin.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 300, 40));

        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Don't have an account?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        lableSignUp.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        lableSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lableSignUp.setText("Sign Up");
        lableSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lableSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableSignUpMouseClicked(evt);
            }
        });
        jPanel2.add(lableSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        lableForgotPassword.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        lableForgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        lableForgotPassword.setText("Forgot Password?");
        lableForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lableForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableForgotPasswordMouseClicked(evt);
            }
        });
        jPanel2.add(lableForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        lableShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/visible.png"))); // NOI18N
        lableShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableShowMouseClicked(evt);
            }
        });
        jPanel2.add(lableShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 30));

        buttonGroup1.add(rbEmployee);
        rbEmployee.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        rbEmployee.setForeground(new java.awt.Color(255, 255, 255));
        rbEmployee.setText("Employee");
        rbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(rbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 410, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        
        
    }
    
    private boolean isEmpty () {
        if(txtUserName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "User name is required","Warning",2);
            return false;
        }
        if(String.valueOf(txtPassword.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password is required","Warning",2);
            return false;
        }
        return true;
    }

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void rbtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAdminActionPerformed

    private void rbtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnUserActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.1; i <= 1.0; i += 0.1) {
            String s = "" + i;
            float f = Float.parseFloat(s);
            this.setOpacity(f);
            try {
                Thread.sleep(40);
            } catch (InterruptedException ex) {
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void lableSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableSignUpMouseClicked
        // TODO add your handling code here:
        new SignUP().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lableSignUpMouseClicked

    private void lableForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableForgotPasswordMouseClicked
        // TODO add your handling code here:
        new ForgotPassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lableForgotPasswordMouseClicked

    private void labelHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHideMouseClicked
        // TODO add your handling code here:
        txtPassword.setEchoChar((char) 0);
        labelHide.setVisible(false);
        lableShow.setVisible(true);
    }//GEN-LAST:event_labelHideMouseClicked

    private void lableShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableShowMouseClicked
        // TODO add your handling code here:
        txtPassword.setEchoChar((char) '*');
        labelHide.setVisible(true);
        lableShow.setVisible(false);
    }//GEN-LAST:event_lableShowMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(isEmpty()) {
            if(rbtnUser.isSelected()) {
                String username = txtUserName.getText();
                String password = String.valueOf(txtPassword.getPassword());
                 if(userController.searchAccount(username, password)) {
                userDashBoard ud = new userDashBoard(username);
                ud.setVisible(true);
                ud.pack();
            }
                 else {
                     JOptionPane.showMessageDialog(this, "Username or Password is not correct or not existed", "Login Failed", 2);
                 }
            }  else if(rbEmployee.isSelected()){
                String username = txtUserName.getText();
                String password = String.valueOf(txtPassword.getPassword());
                 if(userController.searchAccountEmployee(username, password)) {
                Employee_Dashboard ud = new Employee_Dashboard(username);
                ud.setVisible(true);
                ud.pack();
                   }
            }
            else if(rbtnAdmin.isSelected()){
                String username = txtUserName.getText();
                String password = String.valueOf(txtPassword.getPassword());
                 if(userController.searchAccountEmployee(username, password)) {
                     AdminDashBoard ud = new AdminDashBoard(username);
                ud.setVisible(true);
                ud.pack();}}
            
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void rbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmployeeActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_rbEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelHide;
    private javax.swing.JLabel lableForgotPassword;
    private javax.swing.JLabel lableShow;
    private javax.swing.JLabel lableSignUp;
    private javax.swing.JRadioButton rbEmployee;
    private javax.swing.JRadioButton rbtnAdmin;
    private javax.swing.JRadioButton rbtnUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
