/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import OrderProduct.OrderProduct;
import User.com.mycompany.bhx.PrivateAccount;
import SignInUp.Login;
import static User.com.mycompany.bhx.CustomerFuction.idCustomer;
import WriteFeedback.WriteFeedbackFrame;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class userDashBoard extends javax.swing.JFrame {
    
     
      

    /**
     * Creates new form userDashBoard
     */
    public userDashBoard() {
        initComponents();
     
//        lblAccountUser.setText(data1.getLoginName());
//        lblAccountUser.setText(SharedData.getLoginName());

    }

    public userDashBoard(String username) {
        initComponents();
        lblAccountUser.setText(username);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAccountUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPOrderProductSelect = new javax.swing.JPanel();
        JPOrderProduct = new javax.swing.JPanel();
        lblOrderProduct = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPMyAccount = new javax.swing.JPanel();
        jPMyaccountSelect = new javax.swing.JPanel();
        lblMyAccount = new javax.swing.JLabel();
        jpFeedbackSelected = new javax.swing.JPanel();
        lblFeedback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpFeedBack = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(64, 194, 150));

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping.png"))); // NOI18N
        jLabel1.setText("Bach Hoa Xanh Online Shopping");

        lblAccountUser.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        lblAccountUser.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account_light.png"))); // NOI18N
        lblAccountUser.setText("USERNAME");
        lblAccountUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lblAccountUser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAccountUser))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 60));

        jPanel3.setBackground(new java.awt.Color(42, 58, 73));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setForeground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Cascadia Code", 0, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard.png"))); // NOI18N
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 50));

        jPanel5.setBackground(new java.awt.Color(42, 58, 73));

        jPOrderProductSelect.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPOrderProductSelectLayout = new javax.swing.GroupLayout(jPOrderProductSelect);
        jPOrderProductSelect.setLayout(jPOrderProductSelectLayout);
        jPOrderProductSelectLayout.setHorizontalGroup(
            jPOrderProductSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPOrderProductSelectLayout.setVerticalGroup(
            jPOrderProductSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JPOrderProduct.setBackground(new java.awt.Color(42, 58, 73));
        JPOrderProduct.setPreferredSize(new java.awt.Dimension(256, 48));

        javax.swing.GroupLayout JPOrderProductLayout = new javax.swing.GroupLayout(JPOrderProduct);
        JPOrderProduct.setLayout(JPOrderProductLayout);
        JPOrderProductLayout.setHorizontalGroup(
            JPOrderProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        JPOrderProductLayout.setVerticalGroup(
            JPOrderProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        lblOrderProduct.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        lblOrderProduct.setForeground(new java.awt.Color(102, 102, 102));
        lblOrderProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/purchase_dark.png"))); // NOI18N
        lblOrderProduct.setText("Order Product");
        lblOrderProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPOrderProductSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrderProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOrderProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOrderProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPOrderProductSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPOrderProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jPanel7.setBackground(new java.awt.Color(42, 58, 73));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jPanel9.setBackground(new java.awt.Color(51, 255, 102));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPMyAccount.setBackground(new java.awt.Color(42, 58, 73));

        javax.swing.GroupLayout jPMyAccountLayout = new javax.swing.GroupLayout(jPMyAccount);
        jPMyAccount.setLayout(jPMyAccountLayout);
        jPMyAccountLayout.setHorizontalGroup(
            jPMyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jPMyAccountLayout.setVerticalGroup(
            jPMyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPMyaccountSelect.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPMyaccountSelectLayout = new javax.swing.GroupLayout(jPMyaccountSelect);
        jPMyaccountSelect.setLayout(jPMyaccountSelectLayout);
        jPMyaccountSelectLayout.setHorizontalGroup(
            jPMyaccountSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPMyaccountSelectLayout.setVerticalGroup(
            jPMyaccountSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblMyAccount.setBackground(new java.awt.Color(255, 255, 255));
        lblMyAccount.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        lblMyAccount.setForeground(new java.awt.Color(102, 102, 102));
        lblMyAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account_dark.png"))); // NOI18N
        lblMyAccount.setText("My account");
        lblMyAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMyAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jPMyaccountSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPMyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jPMyaccountSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, -1));

        jpFeedbackSelected.setBackground(new java.awt.Color(102, 102, 102));
        jpFeedbackSelected.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jpFeedbackSelectedLayout = new javax.swing.GroupLayout(jpFeedbackSelected);
        jpFeedbackSelected.setLayout(jpFeedbackSelectedLayout);
        jpFeedbackSelectedLayout.setHorizontalGroup(
            jpFeedbackSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jpFeedbackSelectedLayout.setVerticalGroup(
            jpFeedbackSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jpFeedbackSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 20, 50));

        lblFeedback.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(102, 102, 102));
        lblFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_supplier_dark.png"))); // NOI18N
        lblFeedback.setText("Feedback for Us");
        lblFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFeedbackMouseClicked(evt);
            }
        });
        jPanel3.add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel2.setText("LOG OUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 113, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 660));

        javax.swing.GroupLayout jpFeedBackLayout = new javax.swing.GroupLayout(jpFeedBack);
        jpFeedBack.setLayout(jpFeedBackLayout);
        jpFeedBackLayout.setHorizontalGroup(
            jpFeedBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jpFeedBackLayout.setVerticalGroup(
            jpFeedBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jpFeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 10, 50));
        jpFeedBack.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Do you want to logout now?",
                "Logout",JOptionPane.YES_NO_OPTION);
        if(a == 0) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblMyAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyAccountMouseClicked
        // TODO add your handling code here:
        ResetColor();
        lblMyAccount.setForeground(Color.WHITE);
        jPMyAccount.setBackground(  new Color(102,102,255));
        jPMyaccountSelect.setBackground(new Color(64,194,150));
        PrivateAccount a = new PrivateAccount(lblAccountUser.getText());
        a.setVisible(true);
        
        
        
    }//GEN-LAST:event_lblMyAccountMouseClicked

    private void ResetColor(){
        lblMyAccount.setForeground(new Color(102,102,102));
        jPMyAccount.setBackground(  new Color(42,58,73));
        jPMyaccountSelect.setBackground(new Color(102,102,102));
        lblOrderProduct.setForeground(new Color(102,102,102));
        JPOrderProduct.setBackground(  new Color(42,58,73));
        jPOrderProductSelect.setBackground(new Color(102,102,102));
        lblFeedback.setForeground(new Color(102,102,102));
        jpFeedBack.setBackground(  new Color(42,58,73));
        jpFeedbackSelected.setBackground(new Color(102,102,102));
        
    }
    private void lblOrderProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderProductMouseClicked
        // TODO add your handling code here:
        ResetColor();
          lblOrderProduct.setForeground(Color.WHITE);
        JPOrderProduct.setBackground(  new Color(102,102,255));
        jPOrderProductSelect.setBackground(new Color(64,194,150));
       int a = idCustomer(lblAccountUser.getText());
       OrderProduct b = new OrderProduct(a);
       b.setVisible(true);
    }//GEN-LAST:event_lblOrderProductMouseClicked

    private void lblFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFeedbackMouseClicked
        // TODO add your handling code here:
        ResetColor();
          lblFeedback.setForeground(Color.WHITE);
       jpFeedBack.setBackground(  new Color(102,102,255));
        jpFeedbackSelected.setBackground(new Color(64,194,150));
        WriteFeedbackFrame a = new WriteFeedbackFrame(lblAccountUser.getText());
        a.setVisible(true);
       

        
    }//GEN-LAST:event_lblFeedbackMouseClicked

    private void lblAccountUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountUserMouseClicked
        // TODO add your handling code here:
        PrivateAccount a = new PrivateAccount(lblAccountUser.getText());
        a.setVisible(true);
    }//GEN-LAST:event_lblAccountUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOrderProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPMyAccount;
    private javax.swing.JPanel jPMyaccountSelect;
    private javax.swing.JPanel jPOrderProductSelect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jpFeedBack;
    private javax.swing.JPanel jpFeedbackSelected;
    private javax.swing.JLabel lblAccountUser;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblMyAccount;
    private javax.swing.JLabel lblOrderProduct;
    // End of variables declaration//GEN-END:variables
}



